export
  type LayoutParamAttributes = {}
    | MainTypes.TableLayoutLayoutParamsAttributes
    | MainTypes.ActionMenuViewLayoutParamsAttributes
    | MainTypes.RelativeLayoutLayoutParamsAttributes
    | MainTypes.AbsListViewLayoutParamsAttributes
    | MainTypes.FrameLayoutLayoutParamsAttributes
    | MainTypes.RadioGroupLayoutParamsAttributes
    | MainTypes.TableRowLayoutParamsAttributes
    | MainTypes.LinearLayoutLayoutParamsAttributes
    | MainTypes.GridLayoutLayoutParamsAttributes
    | MainTypes.ViewGroupLayoutParamsAttributes
    | MainTypes.ToolbarLayoutParamsAttributes
    | MainTypes.ViewGroupMarginLayoutParamsAttributes
    | AppcompatTypes.LinearLayoutCompatLayoutParamsAttributes
    | AppcompatTypes.ActionMenuViewLayoutParamsAttributes
    | AppcompatTypes.ToolbarLayoutParamsAttributes
    | CoordinatorlayoutTypes.CoordinatorLayoutLayoutParamsAttributes
    | DrawerlayoutTypes.DrawerLayoutLayoutParamsAttributes
    | ComponentsMaterialTypes.AppBarLayoutLayoutParamsAttributes
    | ComponentsMaterialTypes.CollapsingToolbarLayoutLayoutParamsAttributes
    | ComponentsMaterialTypes.ChipGroupLayoutParamsAttributes
    | RecyclerviewTypes.GridLayoutManagerLayoutParamsAttributes
    | RecyclerviewTypes.RecyclerViewLayoutParamsAttributes
    | RecyclerviewTypes.StaggeredGridLayoutManagerLayoutParamsAttributes
    | WearTypes.BoxInsetLayoutLayoutParamsAttributes
    | ViewpagerTypes.ViewPagerLayoutParamsAttributes
    | SlidingpanelayoutTypes.SlidingPaneLayoutLayoutParamsAttributes
    | LeanbackTypes.BaseCardViewLayoutParamsAttributes
    | GridlayoutTypes.GridLayoutLayoutParamsAttributes;
