package com.laidpack.sourcerer.services.adapters

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.Moshi
import com.squareup.moshi.Types
import java.lang.reflect.Type
import kotlin.reflect.KClass

internal class AutoGeneratedAdapterFactory(
        private val subjectTypesToAutoGeneratedAdapterProvider: (KClass<*>) -> JsonAdapter<*>?
) : JsonAdapter.Factory {
    override fun create(t: Type?, annotations: MutableSet<out Annotation>?, m: Moshi?): JsonAdapter<*>? {
        val type = t ?: return null
        val rawType = Types.getRawType(type)

        return subjectTypesToAutoGeneratedAdapterProvider(rawType.kotlin)
            ?: return null
    }
}
